module.exports = server => {
  require('./posts')(server)
  require('./auth')(server)
  require('./services')(server)
  require('./folders')(server)
  require('./users')(server)
  require('./comments')(server)
  require('./images')(server)
  require('./notifications')(server)
  require('./books')(server)
  require('./pocket')(server)
  require('./locker')(server)
  require('./newsfeed')(server)
  require('./tags')(server)
  require('./youtube')(server)
  require('./listen')(server)
  require('./goals')(server)
}
